# Generated by Django 5.2 on 2025-06-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='education',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
