# Generated by Django 5.1 on 2025-06-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='therapist',
        ),
        migrations.RemoveField(
            model_name='language',
            name='therapist',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='therapist',
        ),
        migrations.RenameField(
            model_name='therapist',
            old_name='education',
            new_name='education_field',
        ),
        migrations.RenameField(
            model_name='therapist',
            old_name='specialization',
            new_name='education_institution',
        ),
        migrations.RenameField(
            model_name='therapist',
            old_name='experience',
            new_name='experience_years',
        ),
        migrations.AddField(
            model_name='therapist',
            name='additional_degrees',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='therapist',
            name='education_degree',
            field=models.CharField(blank=True, choices=[('bachelors', "Bachelor's"), ('masters', "Master's"), ('phd', 'PhD'), ('md', 'MD'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='therapist',
            name='education_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapist',
            name='education_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='experience_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapist',
            name='experience_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='experience_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='experience_organization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='therapist',
            name='experience_position',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='therapist',
            name='experience_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='language_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='therapist',
            name='language_proficiency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='other_languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='therapist',
            name='other_specializations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='therapist',
            name='previous_positions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='therapist',
            name='specialization_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='specialization_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
