# Generated by Django 5.2 on 2025-06-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_therapist_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='availability',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='therapist',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='therapist',
            name='specialization',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
