# Generated by Django 5.2 on 2025-06-12 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_therapistrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistnotification',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.therapistrequest'),
        ),
    ]
