# Generated by Django 5.1 on 2025-06-15 18:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_therapistnotification_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapistnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Therapist Notification', 'verbose_name_plural': 'Therapist Notifications'},
        ),
        migrations.AddField(
            model_name='therapistnotification',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.appointment'),
        ),
        migrations.AddField(
            model_name='therapistnotification',
            name='emergency_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapistnotification',
            name='emergency_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistnotification',
            name='emergency_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistnotification',
            name='emergency_severity',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Severity level from 1 (low) to 10 (critical)', null=True),
        ),
        migrations.AddField(
            model_name='therapistnotification',
            name='emergency_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='therapistnotification',
            name='notification_type',
            field=models.CharField(choices=[('request', 'Therapist Request'), ('appointment', 'Appointment'), ('emergency', 'Emergency'), ('general', 'General')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapistnotification',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='API.patient'),
        ),
        migrations.AlterField(
            model_name='therapistnotification',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.therapistrequest'),
        ),
        migrations.AddIndex(
            model_name='therapistnotification',
            index=models.Index(fields=['therapist', 'is_read'], name='API_therapi_therapi_a5d0f9_idx'),
        ),
        migrations.AddIndex(
            model_name='therapistnotification',
            index=models.Index(fields=['created_at'], name='API_therapi_created_c336d9_idx'),
        ),
        migrations.AddIndex(
            model_name='therapistnotification',
            index=models.Index(fields=['notification_type'], name='API_therapi_notific_c6bd54_idx'),
        ),
    ]
